apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecomm

commonLabels:
  app.kubernetes.io/part-of: ecomm

resources:
  - namespace.yaml
  - catalog.yaml
  - cart.yaml
  - orders.yaml
  - payment.yaml
  - shipping.yaml
images:
  - name: catalog-service
    newName: image-registry.openshift-image-registry.svc:5000/ecomm/catalog-service
    newTag: latest
  - name: cart-service
    newName: image-registry.openshift-image-registry.svc:5000/ecomm/cart-service
    newTag: latest
  - name: orders-service
    newName: image-registry.openshift-image-registry.svc:5000/ecomm/orders-service
    newTag: latest
  - name: payment-service
    newName: image-registry.openshift-image-registry.svc:5000/ecomm/payment-service
    newTag: latest
  - name: shipping-service
    newName: image-registry.openshift-image-registry.svc:5000/ecomm/shipping-service
    newTag: latest

