apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: ecomm-pg-cdc
  namespace: ecomm-streaming
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: "pg-ha-primary.db.svc.cluster.local"
    database.port: "5432"
    database.user: "debezium"
    database.password: "dbz"
    database.dbname: "ecomm"

    plugin.name: "pgoutput"
    slot.name: "dbz_ecomm"
    publication.name: "dbz_pub_ecomm"
    publication.autocreate.mode: "filtered"

    snapshot.mode: "initial"
    topic.prefix: "ecomm"
    schema.include.list: "public"

    # optional but useful:
    decimal.handling.mode: "string"
    time.precision.mode: "connect"

